name: nutrogen
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^13.2.4
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  dio_smart_retry: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_hooks: ^0.20.5
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  image_picker: ^1.0.8
  path_provider: ^2.1.3
  flutter_zoom_drawer: ^3.2.0
  intl: ^0.18.1
  ai_barcode_scanner: ^3.4.3
  pie_chart: ^5.4.0
  flutter_rating_bar: ^4.0.1
  dropdown_button2: ^2.3.9
  month_picker_dialog: ^2.11.2
  photo_manager: ^3.0.0
  path: ^1.9.0
  file_picker: ^8.0.0+1
  emoji_picker_flutter: ^2.2.0
  video_player: ^2.8.6
  photo_view: ^0.14.0
  chewie: ^1.8.1
  record: ^4.4.4
  permission_handler: ^11.0.1
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1
  freezed: ^2.5.2
  json_serializable: ^6.7.1


flutter:

  generate: true
  uses-material-design: true

  fonts:
    - family: Kanit
      fonts:
        - asset: asset/font/kanit_regular.ttf
          weight: 400
        - asset: asset/font/kanit_medium.ttf
          weight: 500
        - asset: asset/font/kanit_semi_bold.ttf
          weight: 600
        - asset: asset/font/kanit_bold.ttf
          weight: 700

    - family: PlusJakartaSans
      fonts:
        - asset: asset/font/plus_jakarta_sans_regular.ttf
          weight: 400
        - asset: asset/font/plus_jakarta_sans_bold.ttf
          weight: 700

  assets:
    - asset/image/svg/
    - asset/image/png/
    - asset/image/jpg/