import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:nutrogen/res/app_assets.dart';
import 'package:nutrogen/res/app_colors.dart';

class AppThemes {
  AppThemes._();

  static ThemeData get lightTheme => _createTheme(
        defaultTheme: ThemeData.light(),
        brightness: Brightness.dark,
        primaryColor: AppColors.darkSilver,
        backgroundColor: AppColors.antiFlashWhite,
        scaffoldBackgroundColor: AppColors.antiFlashWhite,
        textColor: AppColors.eerieBlack,
        elevatedButtonBackground: AppColors.darkMidnightBlue,
        primaryTextColor: AppColors.white,
        bottomSheetSurfaceTintColor: AppColors.white,
        appBarSurfaceTintColor: AppColors.transparent,
        appBarBackgroundColor: AppColors.white,
        dialogBackgroundColor: AppColors.white,
      );

  static ThemeData get darkTheme => _createTheme(
        defaultTheme: ThemeData.dark(),
        brightness: Brightness.light,
      );

  static ThemeData _createTheme({
    required ThemeData defaultTheme,
    Brightness? brightness,
    bool? isApplyElevationOverlayColor,
    Typography? typography,
    MaterialStateProperty<Color?>? chipColor,
    MaterialStateProperty<Color?>? datePickerDayOverlayColor,
    MaterialStateProperty<Color?>? datePickerRangeSelectionOverlayColor,
    MaterialStateProperty<Color?>? dataTableDataRowColor,
    MaterialStateProperty<Color?>? dataTableHeadingRowColor,
    MaterialStateProperty<Color?>? datePickerYearOverlayColor,
    MaterialStateProperty<Color?>? datePickerDayBackgroundColor,
    MaterialStateProperty<Color?>? datePickerDayForegroundColor,
    MaterialStateProperty<Color?>? datePickerYearBackgroundColor,
    MaterialStateProperty<Color?>? datePickerYearForegroundColor,
    MaterialStateProperty<Color?>? datePickerTodayBackgroundColor,
    MaterialStateProperty<Color?>? datePickerTodayForegroundColor,
    MaterialStateProperty<Color?>? switchThumbColor,
    MaterialStateProperty<Color?>? switchTrackColor,
    MaterialStateProperty<Color?>? switchOverlayColor,
    MaterialStateProperty<Color?>? switchTrackOutlineColor,
    MaterialStateProperty<Color?>? radioFillColor,
    MaterialStateProperty<Color?>? radioOverlayColor,
    MaterialStateProperty<Color?>? scrollbarThumbColor,
    MaterialStateProperty<Color?>? scrollbarTrackColor,
    MaterialStateProperty<Color?>? scrollbarTrackBorderColor,
    MaterialStateProperty<Color?>? searchBarShadowColor,
    MaterialStateProperty<Color?>? searchBarOverlayColor,
    MaterialStateProperty<Color?>? searchBarBackgroundColor,
    MaterialStateProperty<Color?>? searchBarSurfaceTintColor,
    MaterialStateProperty<Color?>? tabBarOverlayColor,
    Color? disableColor,
    Color? canvasColor,
    Color? focusColor,
    Color? highlightColor,
    Color? hintColor,
    Color? hoverColor,
    Color? indecatorColor,
    Color? primaryDarkColor,
    Color? primaryLightColor,
    Color? secondaryHeadorColor,
    Color? scaffoldBackgroundColor,
    Color? splashColor,
    Color? unselectedWidgetColor,
    Color? textColor,
    Color? primaryTextColor,
    Color? appBarColor,
    Color? appBarShadowColor,
    Color? appBarBackgroundColor,
    Color? appBarForegroundColor,
    Color? appBarSurfaceTintColor,
    Color? badgeTextColor,
    Color? badgeBackgroundColor,
    Color? bannerShadowColor,
    Color? bannerDividerColor,
    Color? bannerBackgroundColor,
    Color? bannerSurfaceTintColor,
    Color? bottomAppBarColor,
    Color? bottomAppBarShadowColor,
    Color? bottomAppBarSurfaceTintColor,
    Color? bottomNavigationBarBackgroundColor,
    Color? bottomNavigationBarSelectedItemColor,
    Color? bottomNavigationBarUnselectedItemColor,
    Color? bottomSheetShadowColor,
    Color? bottomSheetBackgroundColor,
    Color? bottomSheetBragHandleColor,
    Color? bottomSheetSurfaceTintColor,
    Color? bottomSheetModalBarrierColor,
    Color? bottomSheetModalBackgroundColor,
    Color? buttonFocusColor,
    Color? buttonHoverColor,
    Color? buttonButtonColor,
    Color? buttonSplashColor,
    Color? buttonDisabledColor,
    Color? cardColor,
    Color? cardShadowColor,
    Color? cardSurfaceTintColor,
    Color? chipShadowColor,
    Color? chipDisabledColor,
    Color? chipSelectedColor,
    Color? chipCheckmarkColor,
    Color? chipBackgroundColor,
    Color? chipDeleteIconColor,
    Color? chipSurfaceTintColor,
    Color? chipSelectedShadowColor,
    Color? chipSecondarySelectedColor,
    Color? primaryColor,
    Color? onPrimaryColor,
    Color? secondaryColor,
    Color? onSecondaryColor,
    Color? errorColor,
    Color? onErrorColor,
    Color? backgroundColor,
    Color? onBackgroundColor,
    Color? surfaceColor,
    Color? onSurfaceColor,
    Color? errorContainerColor,
    Color? inversePrimaryColor,
    Color? inverseSurfaceColor,
    Color? onErrorContainerColor,
    Color? onInverseSurfaceColor,
    Color? onPrimaryContainerColor,
    Color? onSecondaryContainerColor,
    Color? onSurfaceVariantColor,
    Color? onTertiaryColor,
    Color? onTertiaryContainerColor,
    Color? outlineColor,
    Color? outlineVariantColor,
    Color? primaryContainerColor,
    Color? scrimColor,
    Color? secondaryContainerColor,
    Color? shadowColor,
    Color? surfaceTintColor,
    Color? surfaceVariantColor,
    Color? tertiaryColor,
    Color? tertiaryContainerColor,
    Color? cupertinoOverridePrimaryColor,
    Color? cupertinoOverrideBarBackgroundColor,
    Color? cupertinoOverridePrimaryContrastingColor,
    Color? cupertinoOverrideScaffoldBackgroundColor,
    Color? datePickerShadowColor,
    Color? datePickerBackgroundColor,
    Color? datePickerDividerColor,
    Color? datePickerSurfaceTintColor,
    Color? datePickerHeaderBackgroundColor,
    Color? datePickerHeaderForegroundColor,
    Color? datePickerRangePickerShadowColor,
    Color? datePickerRangePickerBackgroundColor,
    Color? datePickerRangePickerSurfaceTintColor,
    Color? datePickerRangeSelectionBackgroundColor,
    Color? datePickerRangePickerHeaderBackgroundColor,
    Color? datePickerRangePickerHeaderForegroundColor,
    Color? dialogIconColor,
    Color? dialogShadowColor,
    Color? dialogBackgroundColor,
    Color? dialogSurfaceTintColor,
    Color? dividerColor,
    Color? drawerScrimColor,
    Color? drawerShadowColor,
    Color? drawerBackgroundColor,
    Color? drawerSurfaceTintColor,
    Color? expansionTileBackgroundColor,
    Color? expansionTileIconColor,
    Color? expansionTileTextColor,
    Color? expansionTileCollapsedIconColor,
    Color? expansionTileCollapsedTextColor,
    Color? expansionTileCollapsedBackgroundColor,
    Color? floatingActionButtonFcusColor,
    Color? floatingActionButtonHoverColor,
    Color? floatingActionButtonSplashColor,
    Color? floatingActionButtonBackgroundColor,
    Color? floatingActionButtonForegroundColor,
    Color? iconColor,
    Color? inputDecorationFillColor,
    Color? inputDecorationIconColor,
    Color? inputDecorationFocusColor,
    Color? inputDecorationHoverColor,
    Color? inputDecorationPrefixIconColor,
    Color? inputDecorationSuffixIconColor,
    Color? listTileIconColor,
    Color? listTileTextColor,
    Color? listTileTileColor,
    Color? listTileSelectedColor,
    Color? listTileSelectedTileColor,
    Color? navigationBarShadowColor,
    Color? navigationBarIndicatorColor,
    Color? navigationBarBackgroundColor,
    Color? navigationBarSurfaceTintColor,
    Color? navigationDrawerShadowColor,
    Color? navigationDrawerIndicatorColor,
    Color? navigationDrawerBackgroundColor,
    Color? navigationDrawerSurfaceTintColor,
    Color? navigationRailIndicatorColor,
    Color? navigationRailBackgroundColor,
    Color? popupMenuColor,
    Color? popupMenuShadowColor,
    Color? popupMenuSurfaceTintColor,
    Color? primaryIconColor,
    Color? progressIndicatorColor,
    Color? progressIndicatorLinearTrackColor,
    Color? progressIndicatorCircularTrackColor,
    Color? progressIndicatorRefreshBackgroundColor,
    Color? searchViewDividerColor,
    Color? searchViewBackgroundColor,
    Color? searchViewSurfaceTintColor,
    Color? sliderThumbColor,
    Color? sliderOverlayColor,
    Color? sliderActiveTrackColor,
    Color? sliderDisabledThumbColor,
    Color? sliderInactiveTrackColor,
    Color? sliderActiveTickMarkColor,
    Color? sliderValueIndicatorColor,
    Color? sliderInactiveTickMarkColor,
    Color? sliderDisabledActiveTrackColor,
    Color? sliderSecondaryActiveTrackColor,
    Color? sliderDisabledInactiveTrackColor,
    Color? sliderDisabledActiveTickMarkColor,
    Color? sliderOverlappingShapeStrokeColor,
    Color? sliderDisabledInactiveTickMarkColor,
    Color? sliderDisabledSecondaryActiveTrackColor,
    Color? snackBarActionTextColor,
    Color? snackBarSloseIconColor,
    Color? snackBarBackgroundColor,
    Color? snackBarActionBackgroundColor,
    Color? snackBarDisabledActionTextColor,
    Color? snackBarDisabledActionBackgroundColor,
    Color? tabBarLabelColor,
    Color? tabBardividerColor,
    Color? tabBarIndicatorColor,
    Color? tabBarUnselectedLabelColor,
    Color? extSelectionCursorColor,
    Color? extSelectionSelectionColor,
    Color? extSelectionSelectionHandleColor,
    Color? timePickerDialHandColor,
    Color? timePickerDialTextColor,
    Color? timePickerDayPeriodColor,
    Color? timePickerBackgroundColor,
    Color? timePickerHourMinuteColor,
    Color? timePickerDayPeriodTextColor,
    Color? timePickerEntryModeIconColor,
    Color? timePickerDialBackgroundColor,
    Color? timePickerHourMinuteTextColor,
    Color? toggleColor,
    Color? toggleBorderColor,
    Color? toggleFillColor,
    Color? toggleHoverColor,
    Color? toggleFocusColor,
    Color? toggleSplashColor,
    Color? toggleDisabledColor,
    Color? toggleDisabledBorderColor,
    Color? toggleHighlightColor,
    Color? toggleSelectedBorderColor,
    Color? toggleSelectedColor,
    Color? elevatedButtonBackground,
  }) {
    return defaultTheme.copyWith(
      brightness: brightness,
      applyElevationOverlayColor: isApplyElevationOverlayColor,
      canvasColor: canvasColor,
      cardColor: cardColor,
      dialogBackgroundColor: dialogBackgroundColor,
      disabledColor: disableColor,
      dividerColor: dividerColor,
      focusColor: focusColor,
      highlightColor: highlightColor,
      hintColor: hintColor,
      hoverColor: hoverColor,
      indicatorColor: indecatorColor,
      primaryColorDark: primaryDarkColor,
      primaryColorLight: primaryLightColor,
      primaryColor: primaryColor,
      secondaryHeaderColor: secondaryHeadorColor,
      scaffoldBackgroundColor: scaffoldBackgroundColor,
      shadowColor: shadowColor,
      splashColor: splashColor,
      typography: typography,
      unselectedWidgetColor: unselectedWidgetColor,
      colorScheme: defaultTheme.colorScheme.copyWith(
        primary: primaryColor,
        onPrimary: onPrimaryColor,
        secondary: secondaryColor,
        onSecondary: onSecondaryColor,
        error: errorColor,
        onError: onErrorColor,
        background: backgroundColor,
        onBackground: onBackgroundColor,
        surface: surfaceColor,
        onSurface: onSurfaceColor,
        errorContainer: errorContainerColor,
        inversePrimary: inversePrimaryColor,
        inverseSurface: inverseSurfaceColor,
        onErrorContainer: onErrorContainerColor,
        onInverseSurface: onInverseSurfaceColor,
        onPrimaryContainer: onPrimaryContainerColor,
        onSecondaryContainer: onSecondaryContainerColor,
        onSurfaceVariant: onSurfaceVariantColor,
        onTertiary: onTertiaryColor,
        onTertiaryContainer: onTertiaryContainerColor,
        outline: outlineColor,
        outlineVariant: outlineVariantColor,
        primaryContainer: primaryContainerColor,
        scrim: scrimColor,
        secondaryContainer: secondaryContainerColor,
        shadow: shadowColor,
        surfaceTint: surfaceTintColor,
        surfaceVariant: surfaceVariantColor,
        tertiary: tertiaryColor,
        tertiaryContainer: tertiaryContainerColor,
      ),
      cupertinoOverrideTheme: defaultTheme.cupertinoOverrideTheme?.copyWith(
        primaryColor: cupertinoOverridePrimaryColor,
        barBackgroundColor: cupertinoOverrideBarBackgroundColor,
        primaryContrastingColor: cupertinoOverridePrimaryContrastingColor,
        scaffoldBackgroundColor: cupertinoOverrideScaffoldBackgroundColor,
      ),

      /* -------------------------------------------------------------------------- */
      /*                          DIALOG & TABLE & DIVIDER                          */
      /* -------------------------------------------------------------------------- */

      dataTableTheme: defaultTheme.dataTableTheme.copyWith(
        dataRowColor: dataTableDataRowColor,
        headingRowColor: dataTableHeadingRowColor,
      ),
      dialogTheme: defaultTheme.dialogTheme.copyWith(
        iconColor: dialogIconColor,
        shadowColor: dialogShadowColor,
        backgroundColor: dialogBackgroundColor,
        surfaceTintColor: dialogSurfaceTintColor,
      ),
      dividerTheme: defaultTheme.dividerTheme.copyWith(
        color: dividerColor,
      ),

      /* -------------------------------------------------------------------------- */
      /*                         INPUT & ICONS & INDECATOR                          */
      /* -------------------------------------------------------------------------- */

      searchViewTheme: defaultTheme.searchViewTheme.copyWith(
        dividerColor: searchViewDividerColor,
        backgroundColor: searchViewBackgroundColor,
        surfaceTintColor: searchViewSurfaceTintColor,
      ),
      primaryIconTheme: defaultTheme.primaryIconTheme.copyWith(
        color: primaryIconColor,
      ),
      progressIndicatorTheme: defaultTheme.progressIndicatorTheme.copyWith(
        color: progressIndicatorColor,
        linearTrackColor: progressIndicatorLinearTrackColor,
        circularTrackColor: progressIndicatorCircularTrackColor,
        refreshBackgroundColor: progressIndicatorRefreshBackgroundColor,
      ),
      inputDecorationTheme: defaultTheme.inputDecorationTheme.copyWith(
        fillColor: inputDecorationFillColor,
        iconColor: inputDecorationIconColor,
        focusColor: inputDecorationFocusColor,
        hoverColor: inputDecorationHoverColor,
        prefixIconColor: inputDecorationPrefixIconColor,
        suffixIconColor: inputDecorationSuffixIconColor,
      ),
      iconTheme: defaultTheme.iconTheme.copyWith(
        color: iconColor,
      ),

      /* -------------------------------------------------------------------------- */
      /*                        NAVIGATION & DRAWER & VIEWS                         */
      /* -------------------------------------------------------------------------- */

      navigationDrawerTheme: defaultTheme.navigationDrawerTheme.copyWith(
        shadowColor: navigationDrawerShadowColor,
        indicatorColor: navigationDrawerIndicatorColor,
        backgroundColor: navigationDrawerBackgroundColor,
        surfaceTintColor: navigationDrawerSurfaceTintColor,
      ),
      navigationRailTheme: defaultTheme.navigationRailTheme.copyWith(
        indicatorColor: navigationRailIndicatorColor,
        backgroundColor: navigationRailBackgroundColor,
      ),
      bottomNavigationBarTheme: defaultTheme.bottomNavigationBarTheme.copyWith(
        backgroundColor: bottomNavigationBarBackgroundColor,
        selectedItemColor: bottomNavigationBarSelectedItemColor,
        unselectedItemColor: bottomNavigationBarUnselectedItemColor,
      ),
      drawerTheme: defaultTheme.drawerTheme.copyWith(
        scrimColor: drawerScrimColor,
        shadowColor: drawerShadowColor,
        backgroundColor: drawerBackgroundColor,
        surfaceTintColor: drawerSurfaceTintColor,
      ),
      bottomSheetTheme: defaultTheme.bottomSheetTheme.copyWith(
        shadowColor: bottomSheetShadowColor,
        backgroundColor: bottomSheetBackgroundColor,
        dragHandleColor: bottomSheetBragHandleColor,
        surfaceTintColor: bottomSheetSurfaceTintColor,
        modalBarrierColor: bottomSheetModalBarrierColor,
        modalBackgroundColor: bottomSheetModalBackgroundColor,
      ),
      bannerTheme: defaultTheme.bannerTheme.copyWith(
        shadowColor: bannerShadowColor,
        dividerColor: bannerDividerColor,
        backgroundColor: bannerBackgroundColor,
        surfaceTintColor: bannerSurfaceTintColor,
      ),
      cardTheme: defaultTheme.cardTheme.copyWith(
        color: cardColor,
        shadowColor: cardShadowColor,
        surfaceTintColor: cardSurfaceTintColor,
      ),
      listTileTheme: defaultTheme.listTileTheme.copyWith(
        iconColor: listTileIconColor,
        textColor: listTileTextColor,
        tileColor: listTileTileColor,
        selectedColor: listTileSelectedColor,
        selectedTileColor: listTileSelectedTileColor,
      ),
      badgeTheme: defaultTheme.badgeTheme.copyWith(
        textColor: badgeTextColor,
        backgroundColor: badgeBackgroundColor,
      ),
      chipTheme: defaultTheme.chipTheme.copyWith(
        color: chipColor,
        shadowColor: chipShadowColor,
        disabledColor: chipDisabledColor,
        selectedColor: chipSelectedColor,
        checkmarkColor: chipCheckmarkColor,
        backgroundColor: chipBackgroundColor,
        deleteIconColor: chipDeleteIconColor,
        surfaceTintColor: chipSurfaceTintColor,
        selectedShadowColor: chipSelectedShadowColor,
        secondarySelectedColor: chipSecondarySelectedColor,
      ),
      tooltipTheme: defaultTheme.tooltipTheme,

      /* -------------------------------------------------------------------------- */
      /*                                PICKERS & BARS                              */
      /* -------------------------------------------------------------------------- */

      appBarTheme: defaultTheme.appBarTheme.copyWith(
        color: appBarColor,
        systemOverlayStyle: SystemUiOverlayStyle(
          statusBarIconBrightness: brightness,
          statusBarColor: AppColors.transparent,
          systemNavigationBarColor: AppColors.transparent,
        ),
        shadowColor: appBarShadowColor,
        backgroundColor: appBarBackgroundColor,
        foregroundColor: appBarForegroundColor,
        surfaceTintColor: appBarSurfaceTintColor,
      ),
      bottomAppBarTheme: defaultTheme.bottomAppBarTheme.copyWith(
        color: bottomAppBarColor,
        shadowColor: bottomAppBarShadowColor,
        surfaceTintColor: bottomAppBarSurfaceTintColor,
      ),
      tabBarTheme: defaultTheme.tabBarTheme.copyWith(
        labelColor: tabBarLabelColor,
        dividerColor: tabBardividerColor,
        overlayColor: tabBarOverlayColor,
        indicatorColor: tabBarIndicatorColor,
        unselectedLabelColor: tabBarUnselectedLabelColor,
      ),
      timePickerTheme: defaultTheme.timePickerTheme.copyWith(
        dialHandColor: timePickerDialHandColor,
        dialTextColor: timePickerDialTextColor,
        dayPeriodColor: timePickerDayPeriodColor,
        backgroundColor: timePickerBackgroundColor,
        hourMinuteColor: timePickerHourMinuteColor,
        dayPeriodTextColor: timePickerDayPeriodTextColor,
        entryModeIconColor: timePickerEntryModeIconColor,
        dialBackgroundColor: timePickerDialBackgroundColor,
        hourMinuteTextColor: timePickerHourMinuteTextColor,
      ),
      datePickerTheme: defaultTheme.datePickerTheme.copyWith(
        shadowColor: datePickerShadowColor,
        backgroundColor: datePickerBackgroundColor,
        dividerColor: datePickerDividerColor,
        dayOverlayColor: datePickerDayOverlayColor,
        surfaceTintColor: datePickerSurfaceTintColor,
        yearOverlayColor: datePickerYearOverlayColor,
        dayBackgroundColor: datePickerDayBackgroundColor,
        dayForegroundColor: datePickerDayForegroundColor,
        yearBackgroundColor: datePickerYearBackgroundColor,
        yearForegroundColor: datePickerYearForegroundColor,
        todayBackgroundColor: datePickerTodayBackgroundColor,
        todayForegroundColor: datePickerTodayForegroundColor,
        headerBackgroundColor: datePickerHeaderBackgroundColor,
        headerForegroundColor: datePickerHeaderForegroundColor,
        rangePickerShadowColor: datePickerRangePickerShadowColor,
        rangePickerBackgroundColor: datePickerRangePickerBackgroundColor,
        rangeSelectionOverlayColor: datePickerRangeSelectionOverlayColor,
        rangePickerSurfaceTintColor: datePickerRangePickerSurfaceTintColor,
        rangeSelectionBackgroundColor: datePickerRangeSelectionBackgroundColor,
        rangePickerHeaderBackgroundColor:
            datePickerRangePickerHeaderBackgroundColor,
        rangePickerHeaderForegroundColor:
            datePickerRangePickerHeaderForegroundColor,
      ),
      snackBarTheme: defaultTheme.snackBarTheme.copyWith(
        actionTextColor: snackBarActionTextColor,
        closeIconColor: snackBarSloseIconColor,
        backgroundColor: snackBarBackgroundColor,
        actionBackgroundColor: snackBarActionBackgroundColor,
        disabledActionTextColor: snackBarDisabledActionTextColor,
        disabledActionBackgroundColor: snackBarDisabledActionBackgroundColor,
      ),
      searchBarTheme: defaultTheme.searchBarTheme.copyWith(
        shadowColor: searchBarShadowColor,
        overlayColor: searchBarOverlayColor,
        backgroundColor: searchBarBackgroundColor,
        surfaceTintColor: searchBarSurfaceTintColor,
      ),
      scrollbarTheme: defaultTheme.scrollbarTheme.copyWith(
        thumbColor: scrollbarThumbColor,
        trackColor: scrollbarTrackColor,
        trackBorderColor: scrollbarTrackBorderColor,
      ),
      navigationBarTheme: defaultTheme.navigationBarTheme.copyWith(
        shadowColor: navigationBarShadowColor,
        indicatorColor: navigationBarIndicatorColor,
        backgroundColor: navigationBarBackgroundColor,
        surfaceTintColor: navigationBarSurfaceTintColor,
      ),

      /* -------------------------------------------------------------------------- */
      /*                            BUTTONS & MENU                                  */
      /* -------------------------------------------------------------------------- */

      floatingActionButtonTheme:
          defaultTheme.floatingActionButtonTheme.copyWith(
        focusColor: floatingActionButtonFcusColor,
        hoverColor: floatingActionButtonHoverColor,
        splashColor: floatingActionButtonSplashColor,
        backgroundColor: floatingActionButtonBackgroundColor,
        foregroundColor: floatingActionButtonForegroundColor,
      ),
      radioTheme: defaultTheme.radioTheme.copyWith(
        fillColor: radioFillColor,
        overlayColor: radioOverlayColor,
      ),
      dropdownMenuTheme: defaultTheme.dropdownMenuTheme,
      expansionTileTheme: defaultTheme.expansionTileTheme.copyWith(
        backgroundColor: expansionTileBackgroundColor,
        iconColor: expansionTileIconColor,
        textColor: expansionTileTextColor,
        collapsedIconColor: expansionTileCollapsedIconColor,
        collapsedTextColor: expansionTileCollapsedTextColor,
        collapsedBackgroundColor: expansionTileCollapsedBackgroundColor,
      ),
      popupMenuTheme: defaultTheme.popupMenuTheme.copyWith(
        color: popupMenuColor,
        shadowColor: popupMenuShadowColor,
        surfaceTintColor: popupMenuSurfaceTintColor,
      ),
      buttonBarTheme: defaultTheme.buttonBarTheme,
      buttonTheme: defaultTheme.buttonTheme.copyWith(
        focusColor: buttonFocusColor,
        hoverColor: buttonHoverColor,
        buttonColor: buttonButtonColor,
        splashColor: buttonSplashColor,
        disabledColor: buttonDisabledColor,
        highlightColor: buttonDisabledColor,
        alignedDropdown: true,
      ),
      menuBarTheme: MenuBarThemeData(
        style: defaultTheme.menuBarTheme.style?.copyWith(),
      ),
      menuTheme: MenuThemeData(
        style: defaultTheme.menuTheme.style?.copyWith(),
      ),
      menuButtonTheme: MenuButtonThemeData(
        style: defaultTheme.menuButtonTheme.style?.copyWith(),
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: elevatedButtonBackground,
        ),
      ),
      filledButtonTheme: FilledButtonThemeData(
        style: FilledButton.styleFrom(),
      ),
      iconButtonTheme: IconButtonThemeData(
        style: IconButton.styleFrom(),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(),
      ),
      segmentedButtonTheme: defaultTheme.segmentedButtonTheme.copyWith(
        style: defaultTheme.segmentedButtonTheme.style?.copyWith(),
      ),
      textButtonTheme: TextButtonThemeData(
        style: TextButton.styleFrom(),
      ),
      toggleButtonsTheme: defaultTheme.toggleButtonsTheme.copyWith(
        color: toggleColor,
        borderColor: toggleBorderColor,
        fillColor: toggleFillColor,
        hoverColor: toggleHoverColor,
        focusColor: toggleFocusColor,
        splashColor: toggleSplashColor,
        disabledColor: toggleDisabledColor,
        disabledBorderColor: toggleDisabledBorderColor,
        highlightColor: toggleHighlightColor,
        selectedBorderColor: toggleSelectedBorderColor,
        selectedColor: toggleSelectedColor,
      ),
      sliderTheme: defaultTheme.sliderTheme.copyWith(
        thumbColor: sliderThumbColor,
        overlayColor: sliderOverlayColor,
        activeTrackColor: sliderActiveTrackColor,
        disabledThumbColor: sliderDisabledThumbColor,
        inactiveTrackColor: sliderInactiveTrackColor,
        activeTickMarkColor: sliderActiveTickMarkColor,
        valueIndicatorColor: sliderValueIndicatorColor,
        inactiveTickMarkColor: sliderInactiveTickMarkColor,
        disabledActiveTrackColor: sliderDisabledActiveTrackColor,
        secondaryActiveTrackColor: sliderSecondaryActiveTrackColor,
        disabledInactiveTrackColor: sliderDisabledInactiveTrackColor,
        disabledActiveTickMarkColor: sliderDisabledActiveTickMarkColor,
        overlappingShapeStrokeColor: sliderOverlappingShapeStrokeColor,
        disabledInactiveTickMarkColor: sliderDisabledInactiveTickMarkColor,
        disabledSecondaryActiveTrackColor:
            sliderDisabledSecondaryActiveTrackColor,
      ),
      switchTheme: defaultTheme.switchTheme.copyWith(
        thumbColor: switchThumbColor,
        trackColor: switchTrackColor,
        overlayColor: switchOverlayColor,
        trackOutlineColor: switchTrackOutlineColor,
      ),

      /* -------------------------------------------------------------------------- */
      /*                                    TEXTS                                   */
      /* -------------------------------------------------------------------------- */

      textSelectionTheme: defaultTheme.textSelectionTheme.copyWith(
        cursorColor: extSelectionCursorColor,
        selectionColor: extSelectionSelectionColor,
        selectionHandleColor: extSelectionSelectionHandleColor,
      ),
      primaryTextTheme: defaultTheme.primaryTextTheme.copyWith(
        bodyLarge: defaultTheme.primaryTextTheme.bodyLarge?.copyWith(
          color: primaryTextColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 18.sp,
          fontWeight: FontWeight.w600,
        ),
        bodyMedium: defaultTheme.primaryTextTheme.bodyMedium?.copyWith(
          color: primaryTextColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 16.sp,
          fontWeight: FontWeight.w400,
        ),
        bodySmall: defaultTheme.primaryTextTheme.bodySmall?.copyWith(
          color: primaryTextColor,
          fontFamily: AppAssets.fontKanit,
        ),
        displayLarge: defaultTheme.primaryTextTheme.displayLarge?.copyWith(
          color: primaryTextColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 40.sp,
          fontWeight: FontWeight.w500,
        ),
        displayMedium: defaultTheme.primaryTextTheme.displayMedium?.copyWith(
          color: primaryTextColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 24.sp,
          fontWeight: FontWeight.w500,
        ),
        displaySmall: defaultTheme.primaryTextTheme.displaySmall?.copyWith(
          color: primaryTextColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 22.sp,
          fontWeight: FontWeight.w700,
        ),
        headlineLarge: defaultTheme.primaryTextTheme.headlineLarge?.copyWith(
          color: primaryTextColor,
          fontFamily: AppAssets.fontKanit,
        ),
        headlineMedium: defaultTheme.primaryTextTheme.headlineMedium?.copyWith(
          color: primaryTextColor,
          fontFamily: AppAssets.fontKanit,
        ),
        headlineSmall: defaultTheme.primaryTextTheme.headlineSmall?.copyWith(
          color: primaryTextColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 16.sp,
          fontWeight: FontWeight.w600,
        ),
        labelLarge: defaultTheme.primaryTextTheme.labelLarge?.copyWith(
          color: primaryTextColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 12.sp,
          fontWeight: FontWeight.w400,
        ),
        labelMedium: defaultTheme.primaryTextTheme.labelMedium?.copyWith(
          color: primaryTextColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 10.sp,
          fontWeight: FontWeight.w400,
        ),
        labelSmall: defaultTheme.primaryTextTheme.labelSmall?.copyWith(
          color: primaryTextColor,
          fontFamily: AppAssets.fontKanit,
        ),
        titleLarge: defaultTheme.primaryTextTheme.titleLarge?.copyWith(
          color: primaryTextColor,
          fontFamily: AppAssets.fontKanit,
        ),
        titleMedium: defaultTheme.primaryTextTheme.titleMedium?.copyWith(
          color: primaryTextColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 16.sp,
          fontWeight: FontWeight.w700,
        ),
        titleSmall: defaultTheme.primaryTextTheme.titleSmall?.copyWith(
          color: primaryTextColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 14.sp,
          fontWeight: FontWeight.w400,
        ),
      ),
      textTheme: defaultTheme.textTheme.copyWith(
        bodyLarge: defaultTheme.textTheme.bodyLarge?.copyWith(
          color: textColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 18.sp,
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: defaultTheme.textTheme.bodyMedium?.copyWith(
          color: textColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 16.sp,
          fontWeight: FontWeight.w400,
        ),
        bodySmall: defaultTheme.textTheme.bodySmall?.copyWith(
          color: textColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 14.sp,
          fontWeight: FontWeight.w400,
        ),
        displayLarge: defaultTheme.textTheme.displayLarge?.copyWith(
          color: textColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 40.sp,
          fontWeight: FontWeight.w500,
        ),
        displayMedium: defaultTheme.textTheme.displayMedium?.copyWith(
          color: textColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 24.sp,
          fontWeight: FontWeight.w500,
        ),
        displaySmall: defaultTheme.textTheme.displaySmall?.copyWith(
          color: textColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 22.sp,
          fontWeight: FontWeight.w600,
        ),
        headlineLarge: defaultTheme.textTheme.headlineLarge
            ?.copyWith(color: textColor, fontFamily: AppAssets.fontKanit),
        headlineMedium: defaultTheme.textTheme.headlineMedium?.copyWith(
          color: textColor,
          fontFamily: AppAssets.fontKanit,
        ),
        headlineSmall: defaultTheme.textTheme.headlineSmall?.copyWith(
          color: textColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 16.sp,
          fontWeight: FontWeight.w600,
        ),
        labelLarge: defaultTheme.textTheme.labelLarge?.copyWith(
          color: textColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 12.sp,
          fontWeight: FontWeight.w400,
        ),
        labelMedium: defaultTheme.textTheme.labelMedium?.copyWith(
          color: textColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 10.sp,
          fontWeight: FontWeight.w400,
        ),
        labelSmall: defaultTheme.textTheme.labelSmall
            ?.copyWith(color: textColor, fontFamily: AppAssets.fontKanit),
        titleLarge: defaultTheme.textTheme.titleLarge
            ?.copyWith(color: textColor, fontFamily: AppAssets.fontKanit),
        titleMedium: defaultTheme.textTheme.titleMedium?.copyWith(
          color: textColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 16.sp,
          fontWeight: FontWeight.w500,
        ),
        titleSmall: defaultTheme.textTheme.titleSmall?.copyWith(
          color: textColor,
          fontFamily: AppAssets.fontKanit,
          fontSize: 14.sp,
          fontWeight: FontWeight.w400,
        ),
      ),
    );
  }
}
